packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
  - "tooling/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - electron
  - esbuild
  - unrs-resolver
allowBuilds:
  "@parcel/watcher": true
  electron: true
  esbuild: true
  node-pty: set this to true or false
  unrs-resolver: true
